### ISSUE TITLE
Ability to name test examples

### ISSUE THREAD

**Issue by Machiaweliczny** [unindented/react-styleguidist-visual#12]
Great work with this tool!

I would like to propose small improvement:

Styleguidist allows adding custom props to container:
<pre>
You can add a custom props to an example wrapper:

```jsx { "props": { "className": "checks", "name": "my_test_name" } }
{Button} I’m transparent! {/Button}
```
</pre>

If this was used to name examples: eg. 

`Button_my_test_name.png` then it would be order-independent and more meaningful than `Button_7`.

**Comment by unindented** [comment]
Ah, you can do that today with an undocumented prop `data-description`:

<pre>
```jsx { "props": { "data-description": "my_test_name" } }
{Button} I’m transparent! {/Button}
```
</pre>

**Comment by Machiaweliczny** [comment]
@unindented Thank for help!
