### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by tamlyn** [unindented/react-styleguidist-visual#13]
I was very excited to discover this package today but when I run it against my styleguide it fails with an error. 

```
$ npx styleguidist-visual test --url "https://ui-staging-zpqsip.gateway.ps.semioticsquares.com/"
⠧ Taking screenshot 1 of 164 for viewport desktop
Evaluation failed: TypeError: Cannot read property 'getBoundingClientRect' of null
    at <anonymous>:3:40
```

It works fine on the [example styleguide](https://react-styleguidist.js.org/examples/basic/). Here are the [source files and configs](https://gitlab.coko.foundation/pubsweet/pubsweet/tree/master/packages/styleguide).

Any thoughts?

**Comment by unindented** [comment]
That's weird. It'd have to be these two lines that are throwing: https://github.com/unindented/react-styleguidist-visual/blob/9f2ae3a2c56f635ca00a5b657ab34d8459ee0b2d/src/utils/page.js#L80-L81

So `el` is undefined somehow? I don't get it...

I notice that your page takes a while to load. If you serve the page locally and point `react-styleguidist-visual` to that localhost address, does that change anything?

**Comment by tamlyn** [comment]
No, it fails locally too. Yeah the styleguide is really slow. It's possible we've got something screwy in there.

**Comment by unindented** [comment]
One thing we do at Yammer is wrap each example in a component that uses `IntersectionObserver` to only render when the example enters the viewport: https://github.com/Microsoft/YamUI/blob/f572ef4863f6690a929f2c0962ee5034b37c2da1/src/demos/ExampleWrapper/ExampleWrapper.tsx

We configure Styleguidist to use our wrapper here: https://github.com/Microsoft/YamUI/blob/f572ef4863f6690a929f2c0962ee5034b37c2da1/config/styleguide/config.js#L68-L70

That way we don't have to render a hundred components on the page upfront. Maybe that'd help you too?

(I still have no idea whether this has anything to do with the error you're seeing.)

**Comment by tamlyn** [comment]
It looks like it's just the examples in the "Tokens" section which cause the error. If I remove these, the other components get snapshotted fine.

The tokens section is not actually rendering components from our styleguide, it is rendering dynamically created Styled Components in order to demonstrate values from the theme. Could this be something to do with it?

**Comment by unindented** [comment]
But if it renders fine in Styleguidist, then `react-styleguidist-visual` should be able to grab its bounding rect like any other, right?

**Comment by tamlyn** [comment]
Turns out that while those components render fine in the normal view, they break when rendered in isolated mode. Don't know why yet but would appear to be an upstream issue.

**Comment by unindented** [comment]
Ah, thanks for closing then.
