### ISSUE TITLE
False Positives on Different Sized Images

### ISSUE THREAD

**Issue by chrismohr** [unindented/react-styleguidist-visual#18]
Different sized images that match entirely from top to bottom are considered a match.

I narrowed it down to pixelmatch.

<img width="1446" alt="false_positive" src="https://user-images.githubusercontent.com/601657/40262250-c9a9fe66-5aba-11e8-939d-1b76853ee42b.png">

The latest version of pixelmatch, 4.0.2, from Aug 8, 2016 doesn't include a fix for this that was merged the day after the release. 
https://github.com/mapbox/pixelmatch/commit/5dcbb311090aa1438a9ee91fa9b9cbd53459f7d2#diff-168726dbe96b3ce427e7fedce31bb0bc

Would you accept a patch to compare the length of the two images data, and make a mismatch a failure condition?  (While preserving the image diff, to visually indicate the difference?)

**Comment by unindented** [comment]
@chrismohr sure.
