### ISSUE TITLE
Allow --url to use relative file path

### ISSUE THREAD

**Issue by theZieger** [unindented/react-styleguidist-visual#35]
Hi,

currently **react-styleguidist-visual** only allows to take screenshots of an styleguidist documentation running on a server. I would love to see it also work with a relative path pointing to an HTML file of my choice or to use the `styleguide.config.js` `styleguideDir` entry or fall back to use `./styleguide/index.html`.

I know I could also pass `--url "file:///home/xyz/projectdir/styleguide/index.html"`. But that would just work if I'm the only person working on the project or I could wrap the execution of the test in my own `visualtest.js` (or whatever I would call it).

Since **react-styleguidist-visual** seems to be a drop-in solution for **react-styleguidist** I think it would make sense to add this feature.

I currently managed to load my local `./styleguide/index.html` by changing the `goToUrl` function and add some global variables as follows to `page.js`:

```javascript
const appDirectory = process.cwd();

let styleguideDir = './styleguide';

if (fs.existsSync(appDirectory + '/.styleguide.config.js')) {
  styleguideDir =
    require(appDirectory + '/styleguide.config.js').styleguideDir ||
    styleguideDir;
}

async function goToUrl(page, url, navigationOptions) {
  debug('Navigating to URL %s', chalk.blue(url));

  // no protocol given? try to resolve to file:// protocol
  if (url) {
    if (!~url.indexOf('://')) {
      url = 'file://' + path.resolve(appDirectory, url);
    }
  } else {
    // nothing given? use styleguidist.config.js or fallback to './styleguide/index.html'
    url = 'file://' + path.resolve(appDirectory, styleguideDir + '/index.html');
  }

  return page.goto(url, navigationOptions);
}
```

CLI command I now use inside package.json:

```json
{
  "scripts": {
    "visual": "npx styleguidist-visual test --wait 150 --threshold 0.1"
  },
}
```

Also I removed that `--url` is required inside `cli.js` and `test.js`.

If you want to I can contribute a PR for this in the next days. currently I just wanted to hack around this 'problem' to make my life easier running the test locally without having to worry that I need it to point to a running server or passing in a absolute path no one can work with - without making changes to `package.json`.

Cheers

Eric

**Comment by unindented** [comment]
Sorry, I didn't understand this part:

> I know I could also pass --url "file:///home/xyz/projectdir/styleguide/index.html". But that would just work if I'm the only person working on the project or I could wrap the execution of the test in my own visualtest.js (or whatever I would call it).

Why not pass a relative path there? ` --url "file://./styleguide/index.html"` (note the two slashes)

**Comment by theZieger** [comment]
Sorry for writing confusing paragraphs. It doesn't matter.

`--url "file://./styleguide/index.html"` doesn't work that's why I want to have this feature. And I didn't find any other solution to this then using the absolute file path. That's what my snippet above does. It takes the relative given path and generates the absolute path puppeteer needs to open the html file via the `file://` protocol.

On a Linux machine that would result in a URL like: `file:///home/e.zieger/projects/scc/styleguide/index.html` or on Windows `file://C:/Users/e.zieger/scc/styleguide/index.html`.

**Comment by jalyna** [comment]
For me this was working:

package.json
```
"visual:test": "npx styleguidist build && styleguidist-visual test --url \"file://$(pwd)/styleguide/index.html\""
```

Not sure if this also works on windows.

**Comment by theZieger** [comment]
Thank you @jalyna! Much appreciated. I should have known that this is possible. Even though I'm not that good at shell scripting. But you know sometimes you are blind to see the most obvious thing. :laughing:
Thanks for this really well usage example of pwd!

That is making my PR kind of useless right now. Which is good. But we should add that to the README. So others can also use this.

@unindented what do you think?

Will update my PR in a sec.

**Comment by theZieger** [comment]
PR is updated.
I reset the prior ade code changes and added a small section to the README about running the test locally. Hope that helps others. Thanks again @jalyna. :+1:
